stages:
  train:
    cmd: python train.py
    deps:
    - train.py
    outs:
    - confusion_matrix.png
    
    metrics:
    - metrics.txt:
        cache: false
    
    plots:
    - classes.csv:
        cache: false
